### ISSUE TITLE
fluent-plugin-mysql-replicator installation error

### ISSUE THREAD

**Issue by bilalusean** [y-ken/fluent-plugin-mysql-replicator#16]
[bu@bu ~]$ sudo /usr/sbin/td-agent-gem install fluent-plugin-mysql-replicator

WARN: Unresolved specs during Gem::Specification.reset:

      json (>= 1.4.3)

WARN: Clearing out unresolved specs.

Please report a bug if this causes problems.

Building native extensions.  This could take a while...

ERROR:  Error installing fluent-plugin-mysql-replicator:

	ERROR: Failed to build gem native extension.

    /opt/td-agent/embedded/bin/ruby extconf.rb

checking for ruby/thread.h... *** extconf.rb failed ***

Could not create Makefile due to some reason, probably lack of necessary

libraries and/or headers.  Check the mkmf.log file for more details.  You may

need configuration options.

Provided configuration options:

	--with-opt-dir

	--with-opt-include

	--without-opt-include=${opt-dir}/include

	--with-opt-lib

	--without-opt-lib=${opt-dir}/lib

	--with-make-prog

	--without-make-prog

	--srcdir=.

	--curdir

	--ruby=/opt/td-agent/embedded/bin/ruby

/opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)

You have to install development tools first.

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:598:in `try_cpp'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1078:in `block in have_header'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:929:in `block in checking_for'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:928:in `checking_for'

	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1077:in `have_header'

	from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.4.2 for inspection.

Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/mysql2-0.4.2/gem_make.out

Please help me to sort out from this problem. More than 6 hours I am working but still I cant figure out what is the exact problem

**Comment by y-ken** [comment]
Hi @gworksmobi 
Today, I have released new version of this which fixed some minor problems.
https://rubygems.org/gems/fluent-plugin-mysql-replicator

And for this issue, you can install dependent library before installation.
https://github.com/y-ken/fluent-plugin-mysql-replicator/commit/f0be68049dfe76034adb8629002a2a95b06ff7c7
