### ISSUE TITLE
 mysql_replicator_multi start error: undefined method `thread_create' 

### ISSUE THREAD

**Issue by mir134** [y-ken/fluent-plugin-mysql-replicator#37]
<source>
  @type mysql_replicator_multi  
  manager_host 192.168.63.85
  manager_username root
  manager_password root
  manager_database replicator_manager  
  tag replicator.${name}.${event}.${primary_key}
  
</source>

<match replicator.**>
    @type stdout
</match>

2021-04-07 09:06:37 +0800 [error]: #0 error: undefined method `thread_create' for #<Fluent::Plugin::MysqlReplicatorMultiInput:000000047d59e8>
2021-04-07 09:06:37 +0800 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mysql-replicator-1.0.1/lib/fluent/plugin/in_mysql_replicator_multi.rb:37:in `start'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/compat/call_super_mixin.rb:42:in `start'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:200:in `block in start'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:188:in `each'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:188:in `block in lifecycle'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:175:in `each'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:175:in `lifecycle'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:199:in `start'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:248:in `start'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:147:in `run'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:603:in `block in run_worker'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:840:in `main_process'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:594:in `run_worker'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
C:/opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/bin/fluentd:8:in `<top (required)>'
C:/opt/td-agent/embedded/bin/fluentd:23:in `load'
C:/opt/td-agent/embedded/bin/fluentd:23:in `<main>'

**Comment by mir134** [comment]
I found the problem in  fluent-plugin-mysql-replicator/lib/fluent/plugin/in_mysql_replicator_multi.rb 
class MysqlReplicatorMultiInput < Fluent::Input
 miss   helpers :thread

add helpers :thread  is ok

**Comment by mir134** [comment]
C:\opt\td-agent\embedded\lib\ruby\gems\2.4.0\gems\fluent-plugin-mysql-replicator-1.0.1\lib\fluent\plugin\in_mysql_replicator_multi.rb
