### ISSUE TITLE
mysql_replicator_multi v1.0.1 causes error: undefined method `thread_create'

### ISSUE THREAD

**Issue by m-shimojo** [y-ken/fluent-plugin-mysql-replicator#38]
Hi, I have the same problem as #37.
I'm using:
* td-agnet v3.8.1
* fluent-plugin-mysql-replicator v1.0.1

and when I try to start td-agent, the following error is written to /var/log/td-agent/td-agent.log:
```
2021-10-14 17:05:36 +0900 [error]: #0 error: undefined method `thread_create' for #<Fluent::Plugin::MysqlReplicatorMultiInput:007f9c8085fad8>
2021-10-14 17:05:36 +0900 [error]: #0 /etc/td-agent/vendor/bundle/gems/fluent-plugin-mysql-replicator-1.0.1/lib/fluent/plugin/in_mysql_replicator_multi.rb:37:in `start'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/compat/call_super_mixin.rb:42:in `start'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:200:in `block in start'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `each'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `block in lifecycle'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `each'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `lifecycle'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:199:in `start'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/engine.rb:248:in `start'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/engine.rb:147:in `run'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:607:in `block in run_worker'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:845:in `main_process'
/etc/td-agent/vendor/bundle/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:598:in `run_worker'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.5/lib/fluent/command/fluentd.rb:361:in `<main>'
```

**Comment by m-shimojo** [comment]
Steps to reproduce:
 
- Prepare the following files
  - Gemfile
  ```
  source 'https://rubygems.org'
  
  gem 'fluentd', '1.11.5'
  gem 'fluent-plugin-mysql-replicator', git: 'https://github.com/m-shimojo/fluent-plugin-mysql-replicator', ref: '6cf1bc8'
  ```
  - mysql.conf
   ```
  <source>
    @type mysql_replicator_multi
  
    manager_host 127.0.0.1
    manager_port 3306
    manager_username xxxxxx
    manager_password xxxxxx
    manager_database xxxxxx
  
    tag mysql.${name}
  </source>
  
  <match mysql.**>
    @type stdout
  </match>
  ```
- Start fluentd
  ```sh
  $ BUNDLE_GEMFILE=./Gemfile bundle install
  $ BUNDLE_GEMFILE=./Gemfile bundle exec fluentd --config ./mysql.conf -vv
  ```
- Log after stopping fluentd (with Ctrl + C)
  ```
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: fluentd main process get SIGINT
  2021-10-15 18:07:36 +0900 [info]: fluent/log.rb:329:info: Received graceful stop
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: fluentd main process get SIGTERM
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: getting start to shutdown main process
  2021-10-15 18:07:36 +0900 [info]: #0 fluent/log.rb:329:info: fluentd worker is now stopping worker=0
  2021-10-15 18:07:36 +0900 [info]: #0 fluent/log.rb:329:info: shutting down fluentd worker worker=0
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: calling stop on input plugin type=:mysql_replicator_multi plugin_id="object:2ace434d0cd8"
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: calling stop on output plugin type=:stdout plugin_id="object:2ace4345ebc4"
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: preparing shutdown input plugin type=:mysql_replicator_multi plugin_id="object:2ace434d0cd8"
  2021-10-15 18:07:36 +0900 [info]: #0 fluent/log.rb:329:info: shutting down input plugin type=:mysql_replicator_multi plugin_id="object:2ace434d0cd8"
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: preparing shutdown output plugin type=:stdout plugin_id="object:2ace4345ebc4"
  2021-10-15 18:07:36 +0900 [info]: #0 fluent/log.rb:329:info: shutting down output plugin type=:stdout plugin_id="object:2ace4345ebc4"
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: calling after_shutdown on input plugin type=:mysql_replicator_multi plugin_id="object:2ace434d0cd8"
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: calling after_shutdown on output plugin type=:stdout plugin_id="object:2ace4345ebc4"
  2021-10-15 18:07:36 +0900 [debug]: #0 fluent/log.rb:308:debug: closing input plugin type=:mysql_replicator_multi plugin_id="object:2ace434d0cd8"
  2021-10-15 18:07:37 +0900 [info]: #0 fluent/log.rb:329:info: mysql_replicator_multi: execution finished. :setting_name=>db.table_name :rows_count=>514 :elapsed_time=>0.18 sec
  2021-10-15 18:07:38 +0900 [debug]: #0 fluent/log.rb:308:debug: closing output plugin type=:stdout plugin_id="object:2ace4345ebc4"
  2021-10-15 18:07:38 +0900 [debug]: #0 fluent/log.rb:308:debug: calling terminate on input plugin type=:mysql_replicator_multi plugin_id="object:2ace434d0cd8"
  2021-10-15 18:07:38 +0900 [warn]: #0 fluent/log.rb:350:warn: killing existing thread thread=#<Thread:0x0000559c869e6f38@in_mysql_replicator_flusher@/usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:70 sleep>
  2021-10-15 18:07:38 +0900 [warn]: #0 fluent/log.rb:350:warn: killing existing thread thread=#<Thread:0x0000559c869e5bb0@in_mysql_replicator_pollers_0@/usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:70 sleep>
  2021-10-15 18:07:38 +0900 [warn]: #0 fluent/log.rb:350:warn: thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::MysqlReplicatorMultiInput title=:in_mysql_replicator_flusher thread=#<Thread:0x0000559c869e6f38@in_mysql_replicator_flusher@/usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
  2021-10-15 18:07:38 +0900 [warn]: #0 fluent/log.rb:350:warn: thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::MysqlReplicatorMultiInput title=:in_mysql_replicator_pollers_0 thread=#<Thread:0x0000559c869e5bb0@in_mysql_replicator_pollers_0@/usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
  2021-10-15 18:07:38 +0900 [warn]: #0 fluent/log.rb:350:warn: unexpected error while calling terminate on input plugin plugin=Fluent::Plugin::MysqlReplicatorMultiInput plugin_id="object:2ace434d0cd8" error_class=NoMethodError error="undefined method `join' for nil:NilClass"
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:173:in `block in terminate'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:171:in `each'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:171:in `terminate'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:240:in `block (2 levels) in shutdown'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `each'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `block in lifecycle'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `each'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `lifecycle'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:237:in `block in shutdown'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:300:in `shutdown'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/engine.rb:233:in `stop_phase'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/engine.rb:161:in `run'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:607:in `block in run_worker'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:845:in `main_process'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:598:in `run_worker'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/bin/fluentd:8:in `require'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/lib/ruby/gems/2.5.0/gems/fluentd-1.11.5/bin/fluentd:8:in `<top (required)>'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/bin/fluentd:23:in `load'
    2021-10-15 18:07:38 +0900 [warn]: #0 fluent/root_agent.rb:188:each: /usr/local/bin/fluentd:23:in `<main>'
  2021-10-15 18:07:38 +0900 [debug]: #0 fluent/log.rb:308:debug: calling terminate on output plugin type=:stdout plugin_id="object:2ace4345ebc4"
  2021-10-15 18:07:38 +0900 [info]: fluent/log.rb:329:info: Worker 0 finished with status 0
  ```
